# The latest versions are available at https://quiltmc.org/en/usage/latest-versions/
[versions]
minecraft = "1.20.2"
quilt_mappings = "1.20.2+build.3"

quilt_loom = "1.6.8"
quilt_loader = "0.26.0"

fabric_api = "0.91.6+1.20.2"

modmenu = "8.0.1"
ears = "1.4.6+fabric-1.20.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

modmenu = { module = "maven.modrinth:modmenu", version.ref = "modmenu" }
ears = { module = "maven.modrinth:ears", version.ref = "ears" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
# quilted_fabric_api = ["quilted_fabric_api", "quilted_fabric_api_deprecated"]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version.ref = "quilt_loom" }
